name: dask-cookbook-dev
channels:
  - conda-forge
  - nodefaults

dependencies:
  - jupyter-book
  - jupyterlab>=3
  - jupyter_server<2
  - cfgrib
  - cftime < 1.5
  - dask
  - dask-labextension
  - distributed
  - h5netcdf
  - hvplot
  - ipywidgets
  - jupyterlab-system-monitor
  - matplotlib
  - nbterm
  - nc-time-axis
  - netcdf4
  - nodejs
  - pandas
  - pip
  - pre-commit
  - pydap
  - python-graphviz
  - python=3.9
  - scipy
  - xarray>=2022.3.0
  - pip
  - pip:
      - sphinx-pythia-theme
