name: dask-cookbook
channels:
  - conda-forge
  - nodefaults

dependencies:
  - jupyter-book
  - jupyterlab >=3
  - jupyter_server
  - cfgrib
  - cftime
  - dask
  - dask-labextension
  - distributed
  - h5netcdf
  - hvplot
  - ipywidgets
  - jupyterlab-system-monitor
  - matplotlib
  - nbterm
  - nc-time-axis
  - netcdf4
  - nodejs
  - pandas
  - pre-commit
  - pydap
  - python-graphviz
  - scipy
  - sphinx-pythia-theme
  - xarray
  - mystmd
