name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  ACCESS_TOKEN: ${{ secrets.GH_PAT }}
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  
jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: dask-cookbook-dev

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
